[package]
build = 'build.rs'
edition = '2021'
name = 'ton_labs_assembler'
version = '1.4.30'

[dependencies]
failure = '0.1'
hex = '0.4'
log = '0.4'
num = '0.4'
num-traits = '0.2'
serde_json = '1.0'
clap = { features = [ 'derive' ], version = '4.3' }
serde = { features = [ 'derive' ], version = '1.0' }
ton_types = { git = 'ssh://git@github.com/tonlabs/ever-types-private.git', tag = '2.0.31' }
ton_vm = { git = 'ssh://git@github.com/tonlabs/ever-vm-private.git', tag = '1.8.226' }

[dev-dependencies]
similar = '2.2.0'

[features]
gosh = [  ]
groth = [  ]

